export const MAIN_ROUTE = '/fast_company'
export const LOGIN_ROUTE = '/fast_company/login'
export const NEW_USER_ROUTE = '/fast_company/new_user'
export const NEW_USER_EDIT_ROUTE = '/fast_company/new_user/edit'
export const LOGOUT_ROUTE = '/fast_company/logout'
export const USERS_ROUTE = '/fast_company/users'
