export const MAIN_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const NEW_USER_ROUTE = '/new_user'
export const NEW_USER_EDIT_ROUTE = '/new_user/edit'
export const LOGOUT_ROUTE = '/logout'
export const USERS_ROUTE = '/users'
